### ISSUE TITLE
Support for benchmarking HuggingFace models

### ISSUE THREAD

**Issue by varadhbhatnagar** [BloopAI/COBOLEval#3]
Hi @ggordonhall 

I can see in this [blogpost](https://bloop.ai/blog/evaluating-llms-on-cobol) that CodeLlama and mAInframer have been benchmarked on the COBOLEval benchmark. Is there any support in this repo to work directly with Huggingface model checkpoints ?

**Comment by ggordonhall** [comment]
Hey @varadhbhatnagar

https://github.com/BloopAI/COBOLEval/pull/5 adds support to work directly with Huggingface models. It adds two `LLMGenerators`: `HuggingfaceComplete` and `HuggingfaceInfill` (which implements the FIM strategy described in the blogpost).

**Comment by GitMensch** [comment]
Can you recheck with the DeepSeek-R1 models and update your blog post?
Of course it would also be quite nice to see a mAInframerDS based on this model...

**Comment by ggordonhall** [comment]
Yes! The results are due a refresh with the latest crop of models.
