### ISSUE TITLE
Support for FIM based prompting

### ISSUE THREAD

**Issue by varadhbhatnagar** [BloopAI/COBOLEval#4]
As mentioned in this [blogpost](https://bloop.ai/blog/evaluating-llms-on-cobol), there is a FIM based way to prompt the models followed by rearranging the prompt + output so that the Working Storage Section and Linkage Section are in correct order. Do you plan to add support for this style of prompting in this repo?

I am assuming that the `Pass@1` and `%Compile` scores mentioned in the blog are **without** using FIM based prompting?

**Comment by ggordonhall** [comment]
Added support in https://github.com/BloopAI/COBOLEval/pull/5/files.

`Pass@1` and `%Compile` were calculated using FIM based prompting.
